on:
  push:
    branches:
      - "main"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: deploy
        run: |
          git config --global user.name 'auto deploy'
          git config --global user.email 'spdconvos@users.noreply.github.com'
          git remote set-url origin https://github.com/$GITHUB_REPOSITORY
          git checkout $GITHUB_HEAD_REF
          git remote add deploy ${{ secrets.glitch_git_URL }}
          git push -u deploy main
