on:
  pull_request:
    types: [closed]

jobs:
  deploy:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
    - name: deploy
      run: |
        git checkout main
        git remote add deploy ${{ secrets.glitch_git_URL }}
        git push deploy main:main
